name: linux teting 

on:
  workflow_dispatch:
  # pull_request:
  #   types: [opened, synchronize, reopened, closed]
  push:
    branches:
     - master
     - develop
     - release

env:
  # AZURE_WEBAPP_NAME: "app-munson-api-eastus-dev-001"
  ArtifactName: "TEST"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
        
      - name: Restore dependencies
        run: dotnet restore CircleApp.sln

      - name: Build
        run: dotnet build CircleApp/CircleApp.csproj --configuration Release --no-restore
        
      - name: Publish project
        run: dotnet publish CircleApp/CircleApp.csproj --configuration Release --output ./publish

      - name: Create deployment zip
        run: |
          cd ./publish
          zip -r ../CircleApp.zip .
          cd ..
  
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: CircleAppPackage
          path: CircleApp.zip

  deployOnDev:
    runs-on: runner1
    needs: build
    # if: github.base_ref == 'master'
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
          name: CircleAppPackage
          path: CircleAppPackage

    - name: Install Python and pywinrm
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip3 install pywinrm
        
    - name: Deploy artifact to IIS via WinRM
      env:
        WINRM_HOST: ${{ secrets.IIS_SERVER }}
        WINRM_USER: ${{ secrets.IIS_USER }}
        WINRM_PASS: ${{ secrets.IIS_PASSWORD }}
      run: |
        python3 <<EOF
        import winrm
        import base64
        
        remote_zip = r'C:\Temp\CircleApp.zip'
        local_zip = 'CircleAppPackage\CircleApp.zip'
        
        # Read file and encode as base64
        with open(local_zip, 'rb') as f:
            b64 = base64.b64encode(f.read()).decode('utf-8')
        
        # Connect to remote server
        s = winrm.Session(
            '${{ secrets.IIS_SERVER }}',
            auth=('${{ secrets.IIS_USER }}', '${{ secrets.IIS_PASSWORD }}'),
            transport='ntlm'
        )
        
        # Write base64 to remote file and decode
        ps_script = f"""
        Set-Content -Path '{remote_zip}.b64' -Value '{b64}'
        $b64 = Get-Content '{remote_zip}.b64' -Raw
        [IO.File]::WriteAllBytes('{remote_zip}', [Convert]::FromBase64String($b64))
        Remove-Item '{remote_zip}.b64'
        Expand-Archive -Path '{remote_zip}' -DestinationPath 'C:\\inetpub\\wwwroot\\CircleApp' -Force
        Restart-WebAppPool -Name 'DefaultAppPool'
        """
        result = s.run_ps(ps_script)
        print(result.std_out.decode())
        print(result.std_err.decode())
        EOF





  
